# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Version
      run: go version

    - name: Run go vet
      run: go vet ./...

    - name: Run go fmt
      run: go fmt ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./internal/env ./lib/dice/ ./lib/dice/roll ./lib/timestamp
